# Generated by Django 2.2.2 on 2021-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211223_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile_image.png', max_length=255, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
