# Generated by Django 2.2.2 on 2021-12-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorUI', '0002_calculatorhistory_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatorHistory',
        ),
    ]
